name: build-deploy
on:
  workflow_call:
    inputs:
      image:
        type: string
        required: true
      app_uuid:
        type: string
        required: true
      build_args:
        type: string
        required: false
        default: ''
      dockerfile:
        type: string
        required: false
        default: 'Dockerfile'
      context:
        type: string
        required: false
        default: '.'
    secrets:
      GHCR_TOKEN:
        required: true
      COOLIFY_API_TOKEN:
        required: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "hello"
